deploy_production:
  image: mhart/alpine-node:11.14
  stage: deploy
  environment: Production
  only:
    - master
  before_script:
    - npm install -g firebase-tools
  script:
    - cd ./functions/
    - npm ci
    - firebase use --token $FIREBASE_DEPLOY_KEY
    - npm run deploy
  cache:
    paths:
      - node_modules/
